# Generated by Django 5.2 on 2026-01-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_actual', models.IntegerField(default=0)),
                ('ultimo_numero_emitido', models.IntegerField(default=0)),
            ],
        ),
    ]
